os: osx
osx_image: xcode10.3
language: swift
jobs:
  include:
  - stage: test
      script: xcodebuild test -scheme MagicAppTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.4,name=iPhone X' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
